export const METRICS = [
  {
    id: 'sleep',
    label: 'Sleep',
    unit: 'hrs',
    icon: '💤',
    color: '#185FA5',
    bg: '#E6F1FB',
    dotColor: '#378ADD',
    goal: 8,
    min: 0,
    max: 12,
    step: 0.5,
    inputType: 'number',
    logLabel: 'Hours slept',
    placeholder: '7.5',
    scoreFn: (v) => Math.min(100, Math.round((v / 8) * 100)),
    formatVal: (v) => `${v}h`,
  },
  {
    id: 'water',
    label: 'Water',
    unit: 'glasses',
    icon: '💧',
    color: '#0C447C',
    bg: '#E6F1FB',
    dotColor: '#185FA5',
    goal: 8,
    min: 0,
    max: 16,
    step: 1,
    inputType: 'range',
    logLabel: 'Glasses (250ml)',
    scoreFn: (v) => Math.min(100, Math.round((v / 8) * 100)),
    formatVal: (v) => `${v}gl`,
  },
  {
    id: 'steps',
    label: 'Steps',
    unit: 'steps',
    icon: '👟',
    color: '#0F6E56',
    bg: '#E1F5EE',
    dotColor: '#1D9E75',
    goal: 10000,
    min: 0,
    max: 20000,
    step: 500,
    inputType: 'number',
    logLabel: 'Steps taken',
    placeholder: '8000',
    scoreFn: (v) => Math.min(100, Math.round((v / 10000) * 100)),
    formatVal: (v) => (v >= 1000 ? `${(v / 1000).toFixed(1)}k` : String(v)),
  },
  {
    id: 'mood',
    label: 'Mood',
    unit: '/10',
    icon: '🧠',
    color: '#533AB7',
    bg: '#EEEDFE',
    dotColor: '#7F77DD',
    goal: 10,
    min: 1,
    max: 10,
    step: 1,
    inputType: 'range',
    logLabel: 'Mood score',
    scoreFn: (v) => Math.round(v * 10),
    formatVal: (v) => `${v}/10`,
  },
  {
    id: 'calories',
    label: 'Calories',
    unit: 'kcal',
    icon: '🥗',
    color: '#854F0B',
    bg: '#FAEEDA',
    dotColor: '#EF9F27',
    goal: 2000,
    min: 0,
    max: 4000,
    step: 50,
    inputType: 'number',
    logLabel: 'Calories consumed',
    placeholder: '1800',
    scoreFn: (v) => {
      const diff = Math.abs(v - 2000);
      return Math.max(0, 100 - Math.round(diff / 20));
    },
    formatVal: (v) => `${v}cal`,
  },
  {
    id: 'meditation',
    label: 'Meditation',
    unit: 'min',
    icon: '🧘',
    color: '#993556',
    bg: '#FBEAF0',
    dotColor: '#D4537E',
    goal: 20,
    min: 0,
    max: 60,
    step: 5,
    inputType: 'range',
    logLabel: 'Minutes',
    scoreFn: (v) => Math.min(100, Math.round((v / 20) * 100)),
    formatVal: (v) => `${v}m`,
  },
];

export const SCORE_LABELS = [
  'Log your metrics to get started',
  'Needs attention — keep going',
  'Making progress — stay consistent',
  'Good balance — well done!',
  'Excellent health balance today!',
];

export const SCORE_DETAILS = [
  'Track sleep, hydration, exercise, mood, calories and meditation each day.',
  'Some metrics need attention. Log all six for a full picture.',
  "You're building healthy habits. Keep tracking!",
  'Most metrics look great. Fine-tune the rest.',
  'All metrics on track. Outstanding day!',
];

export function getScoreIndex(score) {
  if (score === 0) return 0;
  if (score < 40) return 1;
  if (score < 60) return 2;
  if (score < 85) return 3;
  return 4;
}
